# Apriori

## Importing the libraries

In [28]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

## Data Preprocessing

In [29]:
df = pd.read_csv('C:/Users/redye/MASTERS YORK/Data Mining/Rule Association/BurgersAndCoals.csv', encoding='latin-1')

## Change the lists of items to columns with binary values

In [30]:
df['Milk'] = df.apply(lambda row: 'Milk' in row['Ê ItemsÊÊ'], axis = 1)
df['Burgers'] = df.apply(lambda row: 'Burgers' in row['Ê ItemsÊÊ'], axis = 1)
df['Buns'] = df.apply(lambda row: 'Buns' in row['Ê ItemsÊÊ'], axis = 1)
df['Ketchup'] = df.apply(lambda row: 'Ketchup' in row['Ê ItemsÊÊ'], axis = 1)
df['Coals'] = df.apply(lambda row: 'Coals' in row['Ê ItemsÊÊ'], axis = 1)
df['Beer'] = df.apply(lambda row: 'Beer' in row['Ê ItemsÊÊ'], axis = 1)

## Remove the Original Columns

In [31]:
df.drop(['Ê ItemsÊÊ'], axis = 1, inplace = True)
df.drop(['TIDÊÊ'], axis=1, inplace=True)
df.head()

    Milk  Burgers   Buns  Ketchup  Coals   Beer
0   True     True   True     True  False  False
1  False     True   True     True   True  False
2   True    False   True    False  False   True
3  False     True   True    False   True   True
4   True    False  False     True  False  False

## Training the Apriori model on the dataset

In [32]:
freq_itemsets = apriori(df, min_support=0.25, use_colnames=True)
freq_itemsets.head()

   support   itemsets
0      0.5     (Milk)
1      0.7  (Burgers)
2      0.8     (Buns)
3      0.7  (Ketchup)
4      0.5    (Coals)

## Derive rules from the itemsets

In [33]:
rules = association_rules(freq_itemsets, metric="confidence", min_threshold=0.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Milk),(Buns),0.5,0.8,0.4,0.800000,1.000000,0.00,1.00
1,(Buns),(Milk),0.8,0.5,0.4,0.500000,1.000000,0.00,1.00
2,(Milk),(Ketchup),0.5,0.7,0.3,0.600000,0.857143,-0.05,0.75
3,(Burgers),(Buns),0.7,0.8,0.6,0.857143,1.071429,0.04,1.40
4,(Buns),(Burgers),0.8,0.7,0.6,0.750000,1.071429,0.04,1.20
...,...,...,...,...,...,...,...,...,...
98,"(Burgers, Coals)","(Ketchup, Beer)",0.5,0.3,0.3,0.600000,2.000000,0.15,1.75
99,"(Burgers, Beer)","(Ketchup, Coals)",0.4,0.4,0.3,0.750000,1.875000,0.14,2.40
100,"(Coals, Beer)","(Ketchup, Burgers)",0.4,0.6,0.3,0.750000,1.250000,0.06,1.60
101,(Coals),"(Ketchup, Burgers, Beer)",0.5,0.3,0.3,0.600000,2.000000,0.15,1.75
102,(Beer),"(Ketchup, Burgers, Coals)",0.5,0.4,0.3,0.600000,1.500000,0.10,1.50

## Separate only rules that have Coals as antecedent

In [36]:
coals_rules = rules[rules["antecedents"].apply(lambda x: 'Coals' in str(x))]
print(coals_rules.sort_values(by=['confidence'], ascending=False))

                   antecedents               consequents  antecedent support  \
8                      (Coals)                 (Burgers)                 0.5
39            (Ketchup, Coals)                 (Burgers)                 0.4
82         (Coals, Buns, Beer)                 (Burgers)                 0.3
93      (Ketchup, Coals, Beer)                 (Burgers)                 0.3
50               (Coals, Beer)                 (Burgers)                 0.4
70      (Ketchup, Coals, Buns)                 (Burgers)                 0.3
30               (Coals, Buns)                 (Burgers)                 0.4
32                     (Coals)           (Burgers, Buns)                 0.5
28            (Burgers, Coals)                    (Buns)                 0.5
13                     (Coals)                    (Buns)                 0.5
20                     (Coals)                    (Beer)                 0.5
18                     (Coals)                 (Ketchup)                 0.5
48            (Burgers, Coals)                    (Beer)                 0.5
43                     (Coals)        (Ketchup, Burgers)                 0.5
40            (Burgers, Coals)                 (Ketchup)                 0.5
52                     (Coals)           (Burgers, Beer)                 0.5
71      (Burgers, Coals, Buns)                 (Ketchup)                 0.4
86               (Coals, Buns)           (Burgers, Beer)                 0.4
80      (Burgers, Coals, Beer)                    (Buns)                 0.4
79      (Burgers, Coals, Buns)                    (Beer)                 0.4
94      (Burgers, Coals, Beer)                 (Ketchup)                 0.4
77               (Coals, Buns)        (Ketchup, Burgers)                 0.4
96            (Ketchup, Coals)           (Burgers, Beer)                 0.4
73            (Ketchup, Coals)           (Burgers, Buns)                 0.4
59               (Coals, Beer)                    (Buns)                 0.4
68   (Ketchup, Burgers, Coals)                    (Buns)                 0.4
65               (Coals, Beer)                 (Ketchup)                 0.4
63            (Ketchup, Coals)                    (Beer)                 0.4
91   (Ketchup, Burgers, Coals)                    (Beer)                 0.4
58               (Coals, Buns)                    (Beer)                 0.4
100              (Coals, Beer)        (Ketchup, Burgers)                 0.4
56               (Coals, Buns)                 (Ketchup)                 0.4
54            (Ketchup, Coals)                    (Buns)                 0.4
87               (Coals, Beer)           (Burgers, Buns)                 0.4
98            (Burgers, Coals)           (Ketchup, Beer)                 0.5
66                     (Coals)           (Ketchup, Beer)                 0.5
89                     (Coals)     (Burgers, Buns, Beer)                 0.5
83            (Burgers, Coals)              (Buns, Beer)                 0.5
78                     (Coals)  (Ketchup, Burgers, Buns)                 0.5
75            (Burgers, Coals)           (Ketchup, Buns)                 0.5
61                     (Coals)              (Buns, Beer)                 0.5
57                     (Coals)           (Ketchup, Buns)                 0.5
101                    (Coals)  (Ketchup, Burgers, Beer)                 0.5

     consequent support  support  confidence      lift  leverage  conviction
8                   0.7      0.5        1.00  1.428571      0.15         inf
39                  0.7      0.4        1.00  1.428571      0.12         inf
82                  0.7      0.3        1.00  1.428571      0.09         inf
93                  0.7      0.3        1.00  1.428571      0.09         inf
50                  0.7      0.4        1.00  1.428571      0.12         inf
70                  0.7      0.3        1.00  1.428571      0.09         inf
30                  0.7      0.4        1.00  1.428571      0.12         inf
32                  0.6      0.4        0.80  1.333333      0.10        2.00
28                  0.8      0.4        0.80  1.000000      0.00        1.00
13                  0.8      0.4        0.80  1.000000      0.00        1.00
20                  0.5      0.4        0.80  1.600000      0.15        2.50
18                  0.7      0.4        0.80  1.142857      0.05        1.50
48                  0.5      0.4        0.80  1.600000      0.15        2.50
43                  0.6      0.4        0.80  1.333333      0.10        2.00
40                  0.7      0.4        0.80  1.142857      0.05        1.50
52                  0.4      0.4        0.80  2.000000      0.20        3.00
71                  0.7      0.3        0.75  1.071429      0.02        1.20
86                  0.4      0.3        0.75  1.875000      0.14        2.40
80                  0.8      0.3        0.75  0.937500     -0.02        0.80
79                  0.5      0.3        0.75  1.500000      0.10        2.00
94                  0.7      0.3        0.75  1.071429      0.02        1.20
77                  0.6      0.3        0.75  1.250000      0.06        1.60
96                  0.4      0.3        0.75  1.875000      0.14        2.40
73                  0.6      0.3        0.75  1.250000      0.06        1.60
59                  0.8      0.3        0.75  0.937500     -0.02        0.80
68                  0.8      0.3        0.75  0.937500     -0.02        0.80
65                  0.7      0.3        0.75  1.071429      0.02        1.20
63                  0.5      0.3        0.75  1.500000      0.10        2.00
91                  0.5      0.3        0.75  1.500000      0.10        2.00
58                  0.5      0.3        0.75  1.500000      0.10        2.00
100                 0.6      0.3        0.75  1.250000      0.06        1.60
56                  0.7      0.3        0.75  1.071429      0.02        1.20
54                  0.8      0.3        0.75  0.937500     -0.02        0.80
87                  0.6      0.3        0.75  1.250000      0.06        1.60
98                  0.3      0.3        0.60  2.000000      0.15        1.75
66                  0.3      0.3        0.60  2.000000      0.15        1.75
89                  0.3      0.3        0.60  2.000000      0.15        1.75
83                  0.4      0.3        0.60  1.500000      0.10        1.50
78                  0.5      0.3        0.60  1.200000      0.05        1.25
75                  0.5      0.3        0.60  1.200000      0.05        1.25
61                  0.4      0.3        0.60  1.500000      0.10        1.50
57                  0.5      0.3        0.60  1.200000      0.05        1.25
101                 0.3      0.3        0.60  2.000000      0.15        1.75