In [11]:
# K-Nearest Neighbors (K-NN)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
# Importing the dataset
df = pd.read_csv("C:/Users/redye/MASTERS YORK/Data Mining/DecisionTreeClassification - Data/DT Classification - activity 3.4.1.csv")

In [13]:
# using apply function to create new columns containing categorisation of Age, Licence and Polcy
df['Age = High Risk'] = df.apply(lambda row: row["Age of Driver"] <25 or row["Age of Driver"] >74, axis =1)
df['Licence < 4'] = df.apply(lambda row: row["Age of Licence"] <4, axis =1)
df['Policy < 1']  = df.apply(lambda row: row["Age of Policy"] <1, axis =1)
df['First Party Claims'] = df.apply(lambda row: row[5] >0, axis =1)
df['Third Party Claims'] = df.apply(lambda row: row[6] >0, axis =1)
df.head()

,ID,Age of Driver,Age of Licence,Age of Policy,Unspent Convictions,1st Party Claims,3rd Party Claims,No Claims Protection,No Claims,Exp. Driver,Good Driver,Age = High Risk,Licence < 4,Policy < 1,First Party Claims,Third Party Claims
0,1,27,2,3,N,1,0,Y,Y,N,N,False,True,False,True,False
1,2,19,2,0,N,2,0,Y,N,N,N,True,True,True,True,False
2,3,44,21,5,Y,0,0,N,Y,N,N,False,False,False,False,False
3,4,31,7,7,N,0,0,N,Y,N,N,False,False,False,False,False
4,5,38,13,8,N,2,1,Y,N,Y,N,False,False,False,True,True

In [14]:
# reorder the columns with the dependent variables as the last three columns
column_names = ['Age = High Risk', 'Licence < 4', 'Policy < 1', 'First Party Claims', 'Third Party Claims', 
                'Unspent Convictions', 'No Claims Protection', 'No Claims', 'Exp. Driver', 'Good Driver', ]
df = df.reindex(columns=column_names)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age = High Risk       24 non-null     bool
 1   Licence < 4           24 non-null     bool
 2   Policy < 1            24 non-null     bool
 3   First Party Claims    24 non-null     bool
 4   Third Party Claims    24 non-null     bool
 5   Unspent Convictions   24 non-null     object
 6   No Claims Protection  24 non-null     object
 7   No Claims             24 non-null     object
 8   Exp. Driver           24 non-null     object
 9   Good Driver           24 non-null     object
dtypes: bool(5), object(5)
memory usage: 1.2+ KB

In [21]:
df

,Age = High Risk,Licence < 4,Policy < 1,First Party Claims,Third Party Claims,Unspent Convictions,No Claims Protection,No Claims,Exp. Driver,Good Driver
0,False,True,False,True,False,N,Y,Y,N,N
1,True,True,True,True,False,N,Y,N,N,N
2,False,False,False,False,False,Y,N,Y,N,N
3,False,False,False,False,False,N,N,Y,N,N
4,False,False,False,True,True,N,Y,N,Y,N
5,False,False,False,False,True,Y,N,N,N,N
6,False,False,False,False,True,N,Y,Y,Y,N
7,False,False,False,False,False,N,N,Y,Y,Y
8,True,True,False,True,True,N,Y,N,N,N
9,False,False,False,False,True,Y,N,N,N,N
10,False,True,True,False,False,N,N,Y,N,N
11,True,False,False,True,True,N,Y,N,N,N
12,False,False,False,False,False,N,N,Y,Y,Y
13,False,False,False,False,True,N,Y,Y,Y,N
14,False,False,False,True,False,Y,N,N,N,N
15,False,False,True,False,False,N,Y,N,Y,Y
16,True,True,False,False,False,Y,N,N,N,N
17,False,False,False,True,False,N,Y,Y,Y,N
18,False,False,False,False,True,N,N,N,Y,N
19,True,True,True,False,False,N,Y,N,N,Y
20,False,False,False,False,True,Y,N,N,N,N
21,True,True,False,True,False,N,Y,Y,N,N
22,True,True,False,False,False,N,Y,Y,N,N
23,False,False,False,True,True,N,Y,N,Y,N

In [19]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [36]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[False True True False False 'N' 'N' 'Y' 'N']
 [False False False True True 'N' 'Y' 'N' 'Y']
 [True True False False False 'Y' 'N' 'N' 'N']
 [True False False True True 'N' 'Y' 'N' 'N']
 [False False False True False 'Y' 'N' 'N' 'N']
 [False False False True True 'N' 'Y' 'N' 'Y']
 [False False False False False 'N' 'N' 'Y' 'Y']
 [False False False False True 'Y' 'N' 'N' 'N']
 [True True False True False 'N' 'Y' 'Y' 'N']
 [False False True False False 'N' 'Y' 'N' 'Y']
 [False False False True False 'N' 'Y' 'Y' 'Y']
 [True True False False False 'N' 'Y' 'Y' 'N']
 [True True False True True 'N' 'Y' 'N' 'N']
 [False False False False True 'N' 'N' 'N' 'Y']
 [False False False False True 'N' 'Y' 'Y' 'Y']
 [False False False False False 'Y' 'N' 'Y' 'N']]
['N' 'N' 'N' 'N' 'N' 'N' 'Y' 'N' 'N' 'Y' 'N' 'N' 'N' 'N' 'N' 'N']
[[False False False False True 'Y' 'N' 'N' 'N']
 [False False False False True 'N' 'Y' 'Y' 'Y']
 [False False False False False 'N' 'N' 'Y' 'Y']
 [True True True True False 'N' 'Y' 'N' 'N']
 [False True False True False 'N' 'Y' 'Y' 'N']
 [False False False False False 'N' 'N' 'Y' 'N']
 [False False False False True 'Y' 'N' 'N' 'N']
 [True True True False False 'N' 'Y' 'N' 'N']]
['N' 'N' 'Y' 'N' 'N' 'N' 'N' 'Y']

In [37]:
# Encode all of the columns as binary cols
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in range(9):
    X_train[:,i] = le.fit_transform(X_train[:,i])
    X_test[:,i] = le.fit_transform(X_test[:,i])
## Encode the dependent variables
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [38]:
print(X_train)
print(y_train)

[[0 1 1 0 0 0 0 1 0]
 [0 0 0 1 1 0 1 0 1]
 [1 1 0 0 0 1 0 0 0]
 [1 0 0 1 1 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 1 1 0 1 0 1]
 [0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 0 0 0]
 [1 1 0 1 0 0 1 1 0]
 [0 0 1 0 0 0 1 0 1]
 [0 0 0 1 0 0 1 1 1]
 [1 1 0 0 0 0 1 1 0]
 [1 1 0 1 1 0 1 0 0]
 [0 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 1 1 1]
 [0 0 0 0 0 1 0 1 0]]
[0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]

In [42]:
# Training the K-NN model on the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [43]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]]

In [44]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6 0]
 [2 0]]

0.75